package com.probestack.forgestudio.design.service;

import com.probestack.forgestudio.design.exception.ApiException;
import com.probestack.forgestudio.design.logging.BusinessOperationEvent;
import com.probestack.forgestudio.design.logging.BusinessOperationLogger;
import com.probestack.forgestudio.design.model.Cart;
import com.probestack.forgestudio.design.model.CartItem;
import com.probestack.forgestudio.design.model.CartListResponse;
import com.probestack.forgestudio.design.model.CreateCartRequest;
import com.probestack.forgestudio.design.model.UpdateCartRequest;
import com.probestack.forgestudio.design.repository.CreateCartRequestRepository;
import java.lang.Class;
import java.lang.Exception;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.RuntimeException;
import java.lang.String;
import java.lang.System;
import java.lang.Void;
import java.lang.reflect.Method;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.stream.Collectors;
import org.springframework.beans.BeanUtils;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

/**
 * Service layer for CreateCartRequest operations.
 *
 * <p>This service uses MongoDB repository for data persistence.</p>
 *
 * @author Generated by ProbeStack CodeGen
 * <p>Note: Mapper methods use BeanUtils.copyProperties() for automatic field mapping.</p>
 */
@Service
public class CartsService {
    private final CreateCartRequestRepository createCartRequestRepository;

    private final BusinessOperationLogger businessOperationLogger;

    public CartsService(CreateCartRequestRepository createCartRequestRepository,
            BusinessOperationLogger businessOperationLogger) {
        this.createCartRequestRepository = createCartRequestRepository;
        this.businessOperationLogger = businessOperationLogger;
    }

    public ResponseEntity<Cart> createCart(CreateCartRequest createCartRequest) {
        long businessStartedAt = System.nanoTime();
        try {
            // Save the entity to database
            ensureEntityId(createCartRequest);
            CreateCartRequest savedCreateCartRequest = createCartRequestRepository.save(createCartRequest);
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("createCart")
                            .resource("CreateCartRequest")
                            .action("CREATE")
                            .status("SUCCESS")
                            .repository("CreateCartRequestRepository")
                            .collection("cart_checkout_service_carts")
                            .documentId(getEntityId(savedCreateCartRequest))
                            .recordCount(1)
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            // Map entity to response DTO
            Cart response = mapToCart(savedCreateCartRequest);
            return ResponseEntity.status(HttpStatus.CREATED).body(response);
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("createCart")
                            .resource("CreateCartRequest")
                            .action("CREATE")
                            .status("FAILED")
                            .repository("CreateCartRequestRepository")
                            .collection("cart_checkout_service_carts")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_write_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    public ResponseEntity<Void> emptyCart(String cartId) {
        long businessStartedAt = System.nanoTime();
        try {
            // TODO: Implement custom business logic
            // Available repository methods:
            //   - save(entity) - Create or update
            //   - findById(id) - Find by ID
            //   - findAll() - Get all entities
            //   - existsById(id) - Check if exists
            //   - deleteById(id) - Delete by ID
            //   - count() - Count all entities
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("emptyCart")
                            .resource("CreateCartRequest")
                            .action("UNKNOWN")
                            .status("NOT_IMPLEMENTED")
                            .repository("CreateCartRequestRepository")
                            .collection("cart_checkout_service_carts")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            throw ApiException.notImplemented("Generated operation emptyCart requires custom business logic");
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("emptyCart")
                            .resource("CreateCartRequest")
                            .action("UNKNOWN")
                            .status("FAILED")
                            .repository("CreateCartRequestRepository")
                            .collection("cart_checkout_service_carts")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("business_operation_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    public ResponseEntity<Cart> getCartById(String cartId) {
        long businessStartedAt = System.nanoTime();
        try {
            // Retrieve entity by ID from database
            String repositoryId = toRepositoryId(cartId);
            Optional<CreateCartRequest> entity = createCartRequestRepository.findById(repositoryId);
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("getCartById")
                            .resource("CreateCartRequest")
                            .action("READ")
                            .status("SUCCESS")
                            .repository("CreateCartRequestRepository")
                            .collection("cart_checkout_service_carts")
                            .documentId(repositoryId)
                            .recordCount(entity.isPresent() ? 1 : 0)
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            // Map entity to response DTO
            return entity.map(this::mapToCart).map(ResponseEntity::ok).orElseThrow(() -> ApiException.notFound("CreateCartRequest", repositoryId));
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("getCartById")
                            .resource("CreateCartRequest")
                            .action("READ")
                            .status("FAILED")
                            .repository("CreateCartRequestRepository")
                            .collection("cart_checkout_service_carts")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_read_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    public ResponseEntity<CartListResponse> listCarts(String customerId, String state, Integer page,
            Integer size) {
        long businessStartedAt = System.nanoTime();
        try {
            // Retrieve all entities from database
            List<CreateCartRequest> entities = createCartRequestRepository.findAll();
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("listCarts")
                            .resource("CreateCartRequest")
                            .action("READ")
                            .status("SUCCESS")
                            .repository("CreateCartRequestRepository")
                            .collection("cart_checkout_service_carts")
                            .recordCount(entities.size())
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            // Step 1: Map persisted entities to the OpenAPI wrapper item DTOs
            List<Cart> responses = entities.stream().map(this::mapToCart).collect(Collectors.toList());
            // Step 2: Create the OpenAPI list wrapper and populate its list property
            CartListResponse response = new CartListResponse();
            response.setContent(responses);
            // Step 3: Return the wrapper response required by the API contract
            return ResponseEntity.ok(response);
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("listCarts")
                            .resource("CreateCartRequest")
                            .action("READ")
                            .status("FAILED")
                            .repository("CreateCartRequestRepository")
                            .collection("cart_checkout_service_carts")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_read_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    public ResponseEntity<Cart> updateCart(String cartId, UpdateCartRequest updateCartRequest) {
        long businessStartedAt = System.nanoTime();
        try {
            // TODO: Implement custom business logic
            // Available repository methods:
            //   - save(entity) - Create or update
            //   - findById(id) - Find by ID
            //   - findAll() - Get all entities
            //   - existsById(id) - Check if exists
            //   - deleteById(id) - Delete by ID
            //   - count() - Count all entities
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("updateCart")
                            .resource("CreateCartRequest")
                            .action("UNKNOWN")
                            .status("NOT_IMPLEMENTED")
                            .repository("CreateCartRequestRepository")
                            .collection("cart_checkout_service_carts")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            throw ApiException.notImplemented("Generated operation updateCart requires custom business logic");
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("updateCart")
                            .resource("CreateCartRequest")
                            .action("UPDATE")
                            .status("FAILED")
                            .repository("CreateCartRequestRepository")
                            .collection("cart_checkout_service_carts")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_update_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    /**
     * Converts OpenAPI path IDs to the repository ID type.
     */
    private String toRepositoryId(Object id) {
        if (id == null) {
            return null;
        }
        return id.toString();
    }

    /**
     * Assigns a Mongo document ID when the generated model does not have one yet.
     */
    private void ensureEntityId(Object entity) {
        if (entity == null) {
            return;
        }
        try {
            Method getter = entity.getClass().getMethod("getId");
            Object currentId = getter.invoke(entity);
            if (currentId == null || currentId.toString().isBlank()) {
                setEntityId(entity, UUID.randomUUID().toString());
            }
        } catch (Exception ignored) {
            // Generated models are enhanced with getId/setId; ignore if custom code removed them.
        }
    }

    private void setEntityId(Object entity, String id) {
        if (entity == null || id == null) {
            return;
        }
        try {
            Method setter = entity.getClass().getMethod("setId", String.class);
            setter.invoke(entity, id);
        } catch (Exception ignored) {
            // Generated models are enhanced with setId; ignore if custom code removed it.
        }
    }

    private String getEntityId(Object entity) {
        if (entity == null) {
            return null;
        }
        try {
            Method getter = entity.getClass().getMethod("getId");
            Object value = getter.invoke(entity);
            return value != null ? value.toString() : null;
        } catch (Exception ignored) {
            return null;
        }
    }

    private void copyGeneratedId(Object entity, Object response) {
        String id = getEntityId(entity);
        if (id == null || response == null) {
            return;
        }
        for (Method method : response.getClass().getMethods()) {
            if (method.getName().startsWith("set") && method.getName().endsWith("Id") && method.getParameterCount() == 1 && method.getParameterTypes()[0].equals(String.class)) {
                try {
                    method.invoke(response, id);
                    return;
                } catch (Exception ignored) {
                    // Try the next compatible ID setter.
                }
            }
        }
    }

    /**
     * Creates an empty response wrapper for list/search endpoints.
     */
    private <T> T emptyResponse(Class<T> responseType) {
        try {
            T response = responseType.getDeclaredConstructor().newInstance();
            for (Method method : responseType.getMethods()) {
                if (method.getName().startsWith("set") && method.getParameterCount() == 1 && List.class.isAssignableFrom(method.getParameterTypes()[0])) {
                    method.invoke(response, Collections.emptyList());
                }
            }
            return response;
        } catch (Exception ignored) {
            return null;
        }
    }

    /**
     * Calculates elapsed milliseconds for generated business operation logs.
     */
    private Long businessDurationMs(long startedAt) {
        return (System.nanoTime() - startedAt) / 1_000_000L;
    }

    /**
     * Maps CreateCartRequest entity to CartItem response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private CartItem mapToCartItem(CreateCartRequest entity) {
        // Create new response object
        CartItem response = new CartItem();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        copyGeneratedId(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }

    /**
     * Maps CreateCartRequest entity to Cart response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private Cart mapToCart(CreateCartRequest entity) {
        // Create new response object
        Cart response = new Cart();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        copyGeneratedId(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }
}
